variable "aws_region" {
  type    = string
  default = "us-east-1"
}

variable "aws_profile" {
  type    = string
  default = "default"
}

variable "example_secret" {
  type = string
}

# variable "config" {
#   description = "The set of common variables that are generated by the common project config module"
#   type = object({
#     items = any
#   })
# }

variable "name" {
  description = "The name of the canary will be prepended with project and environment name"
  type        = string
  default     = "test-canary-dev"
}

variable "endpoint" {
    description = "the hostname for the canary request"
    type        = string
    default     = "www.google.com"
}

variable "endpointpath" {
    description = "path - appended to the hostname for full api request"
    type        = string
    default     = ""
}

variable "port" {
    description = "port to target request on"
    type        = string
    default     = ""
}